.TH Python 3.6 container image
.PP
This container image includes Python 3.6 as a S2I
\[la]https://github.com/openshift/source-to-image\[ra] base image for your Python 3.6 applications.
Users can choose between RHEL and CentOS based builder images.
The RHEL images are available in the Red Hat Container Catalog
\[la]https://access.redhat.com/containers/\[ra],
the CentOS images are available on Docker Hub
\[la]https://hub.docker.com/r/centos/\[ra],
and the Fedora images are available in Fedora Registry
\[la]https://registry.fedoraproject.org/\[ra]\&.
The resulting image can be run using podman
\[la]https://github.com/containers/libpod\[ra] or
docker
\[la]http://docker.io\[ra]\&.

.PP
Note: while the examples in this README are calling \fB\fCpodman\fR, you can replace any such calls by \fB\fCdocker\fR with the same arguments

.SH Description
.PP
Python 3.6 available as container is a base platform for
building and running various Python 3.6 applications and frameworks.
Python is an easy to learn, powerful programming language. It has efficient high\-level
data structures and a simple but effective approach to object\-oriented programming.
Python's elegant syntax and dynamic typing, together with its interpreted nature,
make it an ideal language for scripting and rapid application development in many areas
on most platforms.

.PP
This container image includes an npm utility
(see base image repository
\[la]https://github.com/sclorg/s2i-base-container/tree/master/base\[ra]),
so users can use it to install JavaScript
modules for their web applications. There is no guarantee for any specific npm or nodejs
version, that is included in the image; those versions can be changed anytime and
the nodejs itself is included just to make the npm work.

.SH Usage
.PP
For this, we will assume that you are using the supported image, available via \fB\fCpython:3.6\fR imagestream tag in Openshift.
Building a simple python\-sample\-app
\[la]https://github.com/sclorg/s2i-python-container/tree/master/3.6/test/setup-test-app\[ra] application
in Openshift can be achieved with the following step:

.PP
.RS

.nf
```
oc new\-app python:3.6\~https://github.com/sclorg/s2i\-python\-container.git \-\-context\-dir=3.6/test/setup\-test\-app/
```

.fi
.RE

.PP
The same application can also be built using the standalone S2I
\[la]https://github.com/openshift/source-to-image\[ra] application on systems that have it available:

.PP
.RS

.nf
```
$ s2i build https://github.com/sclorg/s2i\-python\-container.git \-\-context\-dir=3.6/test/setup\-test\-app/ <image\_name> python\-sample\-app
```

.fi
.RE

.PP
Where \fB\fC<image\_name>\fR is the s2i\-python image you downloaded from RHEL, Centos or Fedora registry
\[la]../README.md#Download\[ra] or built
\[la]../README.md#Build\[ra] from these sources. For example ubi8/python\-36, centos/python\-36\-centos7 or f31/python3.

.PP
\fBAccessing the application:\fP

.PP
.RS

.nf
$ curl 127.0.0.1:8080

.fi
.RE

.SH Environment variables
.PP
To set these environment variables, you can place them as a key value pair into a \fB\fC\&.s2i/environment\fR
file inside your source code repository.
.IP \(bu 2

.PP
\fBAPP\_SCRIPT\fP
.PP
Used to run the application from a script file.
This should be a path to a script file (defaults to \fB\fCapp.sh\fR unless set to null) that will be
run to start the application.
.IP \(bu 2

.PP
\fBAPP\_FILE\fP
.PP
Used to run the application from a Python script.
This should be a path to a Python file (defaults to \fB\fCapp.py\fR unless set to null) that will be
passed to the Python interpreter to start the application.
.IP \(bu 2

.PP
\fBAPP\_MODULE\fP
.PP
Used to run the application with Gunicorn, as documented
here
\[la]http://docs.gunicorn.org/en/latest/run.html#gunicorn\[ra]\&.
This variable specifies a WSGI callable with the pattern
\fB\fCMODULE\_NAME:VARIABLE\_NAME\fR, where \fB\fCMODULE\_NAME\fR is the full dotted path
of a module, and \fB\fCVARIABLE\_NAME\fR refers to a WSGI callable inside the
specified module.
Gunicorn will look for a WSGI callable named \fB\fCapplication\fR if not specified.

.PP
If \fB\fCAPP\_MODULE\fR is not provided, the \fB\fCrun\fR script will look for a \fB\fCwsgi.py\fR
file in your project and use it if it exists.

.PP
If using \fB\fCsetup.py\fR for installing the application, the \fB\fCMODULE\_NAME\fR part
can be read from there. For an example, see
setup\-test\-app
\[la]https://github.com/sclorg/s2i-python-container/tree/master/3.6/test/setup-test-app\[ra]\&.
.IP \(bu 2

.PP
\fBAPP\_HOME\fP
.PP
This variable can be used to specify a sub\-directory in which the application to be run is contained.
The directory pointed to by this variable needs to contain \fB\fCwsgi.py\fR (for Gunicorn) or \fB\fCmanage.py\fR (for Django).

.PP
If \fB\fCAPP\_HOME\fR is not provided, the \fB\fCassemble\fR and \fB\fCrun\fR scripts will use the application's root
directory.
.IP \(bu 2

.PP
\fBAPP\_CONFIG\fP
.PP
Path to a valid Python file with a
Gunicorn configuration
\[la]http://docs.gunicorn.org/en/latest/configure.html#configuration-file\[ra] file.
.IP \(bu 2

.PP
\fBDISABLE\_MIGRATE\fP
.PP
Set this variable to a non\-empty value to inhibit the execution of 'manage.py migrate'
when the produced image is run. This only affects Django projects. See
"Handling Database Migrations" section of Django blogpost on OpenShift blog
\[la]https://blog.openshift.com/migrating-django-applications-openshift-3/\[ra] on suggestions
how/when to run DB migrations in OpenShift environment. Most importantly,
note that running DB migrations from two or more pods might corrupt your database.
.IP \(bu 2

.PP
\fBDISABLE\_COLLECTSTATIC\fP
.PP
Set this variable to a non\-empty value to inhibit the execution of
'manage.py collectstatic' during the build. This only affects Django projects.
.IP \(bu 2

.PP
\fBDISABLE\_SETUP\_PY\_PROCESSING\fP
.PP
Set this to a non\-empty value to skip processing of setup.py script if you
use \fB\fC\-e .\fR in requirements.txt to trigger its processing or you don't want
your application to be installed into site\-packages directory.
.IP \(bu 2

.PP
\fBENABLE\_PIPENV\fP
.PP
Set this variable to use Pipenv
\[la]https://github.com/pypa/pipenv\[ra],
the higher\-level Python packaging tool, to manage dependencies of the application.
This should be used only if your project contains properly formated Pipfile
and Pipfile.lock.
.IP \(bu 2

.PP
\fBPIN\_PIPENV\_VERSION\fP
.PP
Set this variable together with \fB\fCENABLE\_PIPENV\fR to use a specific version of Pipenv.
If not set, the latest stable version from PyPI is installed.
For example \fB\fCPIN\_PIPENV\_VERSION=2018.11.26\fR installs \fB\fCpipenv==2018.11.26\fR\&.
.IP \(bu 2

.PP
\fBENABLE\_MICROPIPENV\fP
.PP
Set this variable to use micropipenv
\[la]https://github.com/thoth-station/micropipenv\[ra],
a lightweight wrapper for pip to support requirements.txt, Pipenv and Poetry lock
files or converting them to pip\-tools compatible output. Designed for containerized Python applications.
Available only for Python 3 images.
.IP \(bu 2

.PP
\fBENABLE\_INIT\_WRAPPER\fP
.PP
Set this variable to a non\-empty value to make use of an init wrapper.
This is useful for servers that are not capable of reaping zombie
processes, such as Django development server or Tornado. This option can
be used together with \fBAPP\_SCRIPT\fP or \fBAPP\_FILE\fP\&. It never applies
to Gunicorn used through \fBAPP\_MODULE\fP as Gunicorn reaps zombie
processes correctly.
.IP \(bu 2

.PP
\fBPIP\_INDEX\_URL\fP
.PP
Set this variable to use a custom index URL or mirror to download required
packages during build process. This affects packages listed in
requirements.txt. It also affects the installation of pipenv and
micropipenv and the update of pip in the container, though if not found in
the custom index, the container will try to install/update them from
upstream PyPI afterwards.
.IP \(bu 2

.PP
\fBUPGRADE\_PIP\_TO\_LATEST\fP
.PP
Set this variable to a non\-empty value to have the 'pip' program and related
python packages (setuptools and wheel) be upgraded to the most recent version
before any Python packages are installed. If not set it will use whatever
the default version is included by the platform for the Python version being used.
.IP \(bu 2

.PP
\fBWEB\_CONCURRENCY\fP
.PP
Set this to change the default setting for the number of
workers
\[la]http://docs.gunicorn.org/en/stable/settings.html#workers\[ra]\&. By
default, this is set to the number of available cores times 2, capped
at 12.

.SH Source repository layout
.PP
You do not need to change anything in your existing Python project's repository.
However, if these files exist they will affect the behavior of the build process:
.IP \(bu 2
\fBrequirements.txt\fP

.PP
List of dependencies to be installed with \fB\fCpip\fR\&. The format is documented
  here
\[la]https://pip.pypa.io/en/latest/user_guide.html#requirements-files\[ra]\&.
.IP \(bu 2
\fBPipfile\fP

.PP
The replacement for requirements.txt, project is currently under active
  design and development, as documented here
\[la]https://github.com/pypa/pipfile\[ra]\&.
  Set \fB\fCENABLE\_PIPENV\fR environment variable to true in order to process this file.
.IP \(bu 2
\fBsetup.py\fP

.PP
Configures various aspects of the project, including installation of
  dependencies, as documented
  here
\[la]https://packaging.python.org/en/latest/distributing.html#setup-py\[ra]\&.
  For most projects, it is sufficient to simply use \fB\fCrequirements.txt\fR or
  \fB\fCPipfile\fR\&. Set \fB\fCDISABLE\_SETUP\_PY\_PROCESSING\fR environment variable to true
  in order to skip processing of this file.

.SH Run strategies
.PP
The container image produced by s2i\-python executes your project in one of the
following ways, in precedence order:
.IP \(bu 2
\fBGunicorn\fP

.PP
The Gunicorn WSGI HTTP server is used to serve your application in the case that it
  is installed. It can be installed by listing it either in the \fB\fCrequirements.txt\fR
  file or in the \fB\fCinstall\_requires\fR section of the \fB\fCsetup.py\fR file.

.PP
If a file named \fB\fCwsgi.py\fR is present in your repository, it will be used as
  the entry point to your application. This can be overridden with the
  environment variable \fB\fCAPP\_MODULE\fR\&.
  This file is present in Django projects by default.

.PP
If you have both Django and Gunicorn in your requirements, your Django project
  will automatically be served using Gunicorn.
.IP \(bu 2
\fBDjango development server\fP

.PP
If you have Django in your requirements but don't have Gunicorn, then your
  application will be served using Django's development web server. However, this is not
  recommended for production environments.
.IP \(bu 2
\fBPython script\fP

.PP
This would be used where you provide a Python code file for running you
  application. It will be used in the case where you specify a path to a
  Python script via the \fB\fCAPP\_FILE\fR environment variable, defaulting to a
  file named \fB\fCapp.py\fR if it exists. The script is passed to a regular
  Python interpreter to launch your application.
.IP \(bu 2
\fBApplication script file\fP

.PP
This is the most general way of executing your application. It will be
  used in the case where you specify a path to an executable script file
  via the \fB\fCAPP\_SCRIPT\fR environment variable, defaulting to a file named
  \fB\fCapp.sh\fR if it exists. The script is executed directly to launch your
  application.

.SH Hot deploy
.PP
If you are using Django, hot deploy will work out of the box.

.PP
To enable hot deploy while using Gunicorn, make sure you have a Gunicorn
configuration file inside your repository with the
\fB\fCreload\fR
\[la]https://gunicorn-docs.readthedocs.org/en/latest/settings.html#reload\[ra]
option set to \fB\fCtrue\fR\&. Make sure to specify your config via the \fB\fCAPP\_CONFIG\fR
environment variable.

.PP
To change your source code in running container, use podman's (or docker's)
exec
\[la]https://github.com/containers/libpod/blob/master/docs/podman-exec.1.md\[ra] command:

.PP
.RS

.nf
podman exec \-it <CONTAINER\_ID> /bin/bash

.fi
.RE

.PP
After you enter into the running container, your current directory is set
to \fB\fC/opt/app\-root/src\fR, where the source code is located.

.SH See also
.PP
Dockerfile and other sources are available on 
\[la]https://github.com/sclorg/s2i-python-container\[ra]\&.
In that repository you also can find another versions of Python environment Dockerfiles.
Dockerfile for CentOS is called \fB\fCDockerfile\fR, Dockerfile for RHEL7 is called \fB\fCDockerfile.rhel7\fR,
for RHEL8 it's \fB\fCDockerfile.rhel8\fR and the Fedora Dockerfile is called \fB\fCDockerfile.fedora\fR\&.
